version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: cargo
  directory: "/src/quacs-rs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
