name: Evaluate site performance
on: push
jobs:
  lighthouse:
    name: Evaluating site performance with Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  12.x

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install wasm-pack
        run: cargo install --git https://github.com/Urhengulas/wasm-pack.git --branch wasm-opt-enable-non-mvp

      - name: Build site
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
